CREATE DATABASE FIFPro
GO

USE FIFPro
GO 

CREATE TABLE ACCOUNT
(
	AC_ID INT IDENTITY PRIMARY KEY, 
	AC_NAME VARCHAR(100) NOT NULL DEFAULT N'no name', 
	AC_PASSWORD VARCHAR(100) NOT NULL, 
	AC_COIN INT NOT NULL, 
	AC_ROLE INT NOT NULL DEFAULT 0, 
	AC_IDTEAM INT, 
)
GO

CREATE TABLE TEAM 
(
	T_ID INT IDENTITY PRIMARY KEY, 
	T_NAME VARCHAR(100) NOT NULL DEFAULT N'no name', 
)
GO

CREATE TABLE FOOTBALLER
(
	
)
GO

ALTER TABLE ACCOUNT ADD
CONSTRAINT FK_AC_T FOREIGN KEY (AC_IDTEAM) REFERENCES TEAM(T_ID)
GO 

ALTER TABLE PHONG NOCHECK CONSTRAINT ALL
ALTER TABLE KHACHSAN NOCHECK CONSTRAINT ALL
ALTER TABLE KHACHHANG NOCHECK CONSTRAINT ALL
GO

INSERT INTO PHONG VALUES
	('PH001', '201', 'KS001', 'Superior Double', 'Trong', 500000),
	('PH002', '202', 'KS001', 'Deluxe King', 'Trong', 1000000),
	('PH003', '203', 'KS002', 'Deluxe King', 'Dang Sua', 1000000)
GO

